apiVersion: apps/v1
kind: Deployment
metadata:
  name: votingapp
  namespace: votingapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: votingapp
  template:
    metadata:
      labels:
        app: votingapp
    spec:
      containers:
      - name: votingapp
        image: sydammani/voting-app:latest
        ports:
        - containerPort: 8080
        env:
        - name: DB_HOST
          value: mysql
